# emojis.py

EMOJI_MAP = {
    "it's a small world": "🌍",
    "Adventure Isle": "🏝️",
    "Alice's Curious Labyrinth": "🃏",
    "Autopia, presented by Avis": "🚗",
    "Avengers Assemble: Flight Force": "🛡️",
    "Big Thunder Mountain": "⛰️",
    "Blanche-Neige et les Sept Nains®": "🍎",
    "Buzz Lightyear Laser Blast": "🔫",
    "Cars Quatre Roues Rallye": "🏁",
    "Cars ROAD TRIP": "🌵",
    "Casey Jr. – le Petit Train du Cirque": "🚂",
    "Crush's Coaster": "🐢",
    "Disneyland Railroad Frontierland Depot": "🚂",
    "Disneyland Railroad Main Street Station": "🚉",
    "Dumbo the Flying Elephant": "🐘",
    "Entry to World of Frozen": "❄️",
    "Frontierland Playground": "🌵",
    "Frozen Ever After": "⛄",
    "Indiana Jones™ and the Temple of Peril": "🤠",
    "La Cabane des Robinson": "🌳",
    "La Tanière du Dragon": "🐉",
    "Le Carrousel de Lancelot ": "🎠",
    "Le Passage Enchanté d'Aladdin": "🧞",
    "Le Pays des Contes de Fées, presented by Vittel": "📖",
    "Les Mystères du Nautilus": "🌀",
    "Les Tapis Volants - Flying Carpets Over Agrabah®": "🧞",
    "Les Voyages de Pinocchio": "🤥",
    "Mad Hatter's Tea Cups": "☕",
    "Main Street Vehicles": "🚔",
    "Orbitron®": "🛰️",
    "Peter Pan's Flight": "🧚",
    "Phantom Manor": "👻",
    "Pirate Galleon": "🏴‍☠️",
    "Pirates of the Caribbean": "⚔️",
    "Pirates' Beach": "🏖️",
    "RC Racer": "🏎️",
    "Raiponce Tangled Spin": "🍳",
    "Ratatouille : L’Aventure Totalement Toquée de Rémy​": "🐭",
    "Rustler Roundup Shootin' Gallery": "🎯",
    "Slinky® Dog Zigzag Spin": "🐶",
    "Spider-Man W.E.B. Adventure": "🕷️",
    "Star Tours: The Adventures Continue*": "🌌",
    "Star Wars Hyperspace Mountain": "🚀",
    "The Twilight Zone Tower of Terror": "🏨",
    "Thunder Mesa Riverboat Landing": "🚢",
    "Toy Soldiers Parachute Drop": "🪂"
}

def get_emoji(name):
    # Retourne l'émoji si trouvé, sinon un émoji par défaut
    return EMOJI_MAP.get(name, "🎡")
