name: 📅 Disney Data Schedule

on:
  schedule:
    # S'exécute à 07:00 UTC tous les jours
    - cron: '0 5 * * *'
  workflow_dispatch: # Permet de lancer le worker manuellement depuis l'onglet Actions
  repository_dispatch:        # Pour les appels externes (Cron-job.org, etc.)
    types: [run-schedule-disney-bot]

jobs:
  update-schedules:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: 🐍 Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Installation des dépendances
        run: |
          pip install requests supabase

      - name: 🚀 Exécution du Scheduler
        env:
          # On récupère tes secrets déjà existants dans le dépôt
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scheduler.py
