# ... (début du fichier identique)
      wait_time:
        description: 'Temps d attente'
        default: '0'
      minutes_ago:
        description: 'Il y a combien de minutes ? (0 pour maintenant)'
        default: '0'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      # ... (setup python et install)
      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python test_manager.py "${{ github.event.inputs.ride_name }}" "${{ github.event.inputs.status }}" "${{ github.event.inputs.wait_time }}" "${{ github.event.inputs.minutes_ago }}"
