name: Sync Disney Weather

on:
  schedule:
    - cron: '*/15 * * * *' # S'exécute toutes les 15 minutes
  workflow_dispatch: # Permet de le lancer manuellement pour tester
  repository_dispatch:        # Pour les appels externes (Cron-job.org, etc.)
    types: [run-all-bot]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests supabase pytz

      - name: Run sync script
        run: python weather_data.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
